### ISSUE TITLE
Error "pq: SSL is not enabled on the server" when using Postgres

### ISSUE THREAD

**Issue by ervan23** [System-Glitch/goyave#25]
## Description

**Version:** v2.3.0  
**Environment:** [OS Windows 10, Go version go1.12.5]  

Now I'm using Postgres as my database client, in `config.json` I already add **dbOptions** `sslmode=disable`, but the error always occurred.

**Relevant logs:** *(if needed)*
```
2020/01/02 17:05:36 pq: SSL is not enabled on the server
goroutine 21 [running]:
runtime/debug.Stack(0x4ebc43, 0xc00008c000, 0x2)
        C:/Go/src/runtime/debug/stack.go:24 +0xa4
runtime/debug.PrintStack()
        C:/Go/src/runtime/debug/stack.go:16 +0x29
github.com/System-Glitch/goyave/v2.(*Response).Error(0xc0001d6920, 0x82b6c0, 0xc0001864e0, 0xc000079638, 0x0)
        C:/Users/Frontend/go/pkg/mod/github.com/!system-!glitch/goyave/v2@v2.3.0/response.go:118 +0x9d
github.com/System-Glitch/goyave/v2.recoveryMiddleware.func1.1(0xc0001d6920)
        C:/Users/Frontend/go/pkg/mod/github.com/!system-!glitch/goyave/v2@v2.3.0/middleware.go:25 +0x52
panic(0x82b6c0, 0xc0001864e0)
        C:/Go/src/runtime/panic.go:522 +0x1c3
github.com/System-Glitch/goyave/v2/database.newConnection(0x894e00)
        C:/Users/Frontend/go/pkg/mod/github.com/!system-!glitch/goyave/v2@v2.3.0/database/database.go:73 +0x2c7
github.com/System-Glitch/goyave/v2/database.GetConnection(...)
        C:/Users/Frontend/go/pkg/mod/github.com/!system-!glitch/goyave/v2@v2.3.0/database/database.go:22
spp-online/database/model.User.GetBy(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        D:/Ervan/Ext/spp-online/database/model/user.go:56 +0x284
spp-online/http/controller/auth.signIn(0xc0001d6920, 0xc0001727d0)
        D:/Ervan/Ext/spp-online/http/controller/auth/auth.go:23 +0x91
github.com/System-Glitch/goyave/v2.validateRequestMiddleware.func1(0xc0001d6920, 0xc0001727d0)
        C:/Users/Frontend/go/pkg/mod/github.com/!system-!glitch/goyave/v2@v2.3.0/middleware.go:135 +0xac
github.com/System-Glitch/goyave/v2.corsMiddleware.func1(0xc0001d6920, 0xc0001727d0)
        C:/Users/Frontend/go/pkg/mod/github.com/!system-!glitch/goyave/v2@v2.3.0/middleware.go:84 +0x160
github.com/System-Glitch/goyave/v2.languageMiddleware.func1(0xc0001d6920, 0xc0001727d0)
        C:/Users/Frontend/go/pkg/mod/github.com/!system-!glitch/goyave/v2@v2.3.0/middleware.go:168 +0xb2
github.com/System-Glitch/goyave/v2.parseRequestMiddleware.func1(0xc0001d6920, 0xc0001727d0)
        C:/Users/Frontend/go/pkg/mod/github.com/!system-!glitch/goyave/v2@v2.3.0/middleware.go:56 +0xfa
github.com/System-Glitch/goyave/v2.recoveryMiddleware.func1(0xc0001d6920, 0xc0001727d0)
        C:/Users/Frontend/go/pkg/mod/github.com/!system-!glitch/goyave/v2@v2.3.0/middleware.go:29 +0x70
github.com/System-Glitch/goyave/v2.(*Router).requestHandler(0xc000171170, 0x940b00, 0xc0001e40e0, 0xc000180b00, 0x8c21b8, 0xc0001709c0)
        C:/Users/Frontend/go/pkg/mod/github.com/!system-!glitch/goyave/v2@v2.3.0/router.go:149 +0x165
github.com/System-Glitch/goyave/v2.(*Router).route.func1(0x940b00, 0xc0001e40e0, 0xc000180b00)
        C:/Users/Frontend/go/pkg/mod/github.com/!system-!glitch/goyave/v2@v2.3.0/router.go:73 +0x61
net/http.HandlerFunc.ServeHTTP(0xc0001d6680, 0x940b00, 0xc0001e40e0, 0xc000180b00)
        C:/Go/src/net/http/server.go:1995 +0x4b
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000e8540, 0x940b00, 0xc0001e40e0, 0xc000206000)
        C:/Users/Frontend/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xea
net/http.serverHandler.ServeHTTP(0xc000050ea0, 0x940b00, 0xc0001e40e0, 0xc000206000)
        C:/Go/src/net/http/server.go:2774 +0xaf
net/http.(*conn).serve(0xc00016d540, 0x941900, 0xc0001ea040)
        C:/Go/src/net/http/server.go:1878 +0x858
created by net/http.(*Server).Serve
        C:/Go/src/net/http/server.go:2884 +0x2fb
```

### How it occurred

Every querying data

### How to reproduce

Every querying data

**Comment by System-Glitch** [comment]
Thank you for reporting this issue. The fix will be available in the next release, coming later this week.
